from .controller.entry import entry_router
from .controller.voguekorea import voguekorea_router
from .controller.fashionchingu import fashionchingu_router
from .controller.eyesmag import eyesmag_router
from .controller.fashioninsight import fashioninsight_router
from .controller.unnielooks import unnielooks_router
from .controller.yesstyle import yesstyle_router
from .controller.kmodes import kmodes_router
from .controller.krazefashion import krazefashion_router
from .controller.krazemedia import krazemedia_router
from .controller.oncuration import oncuration_router
from .controller.harpersbazaar import harpersbazaar_router
from .controller.seoulinspired import seoulinspired_router
